"""Cria a nova estrutura do banco

Revision ID: 8ea1dcb95719
Revises: 
Create Date: 2025-09-10 16:57:45.001632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ea1dcb95719'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único do agendamento.'),
    sa.Column('service_name', sa.String(), nullable=True, comment='Nome do serviço agendado.'),
    sa.Column('pet_id', sa.String(), nullable=True, comment='Identificador único do pet agendado.'),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True, comment='Horário agendado para o serviço.'),
    sa.Column('employee_id', sa.String(), nullable=True, comment='Identificador único do funcionário responsável pelo serviço.'),
    sa.Column('delivery', sa.Boolean(), nullable=True, comment='Indica se o cliente solicitou o serviço de busca e entrega'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_employee_id'), 'bookings', ['employee_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_pet_id'), 'bookings', ['pet_id'], unique=False)
    op.create_index(op.f('ix_bookings_scheduled_time'), 'bookings', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_bookings_service_name'), 'bookings', ['service_name'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único do cliente.'),
    sa.Column('name', sa.String(), nullable=True, comment='Nome do cliente.'),
    sa.Column('phone', sa.String(), nullable=True, comment='Número de telefone do cliente.'),
    sa.Column('address', sa.String(), nullable=True, comment='Endereço do cliente.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_address'), 'customers', ['address'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único do produto no inventário.'),
    sa.Column('product_name', sa.String(), nullable=True, comment='Nome do produto.'),
    sa.Column('quantity', sa.Integer(), nullable=True, comment='Quantidade disponível do produto.'),
    sa.Column('price', sa.Float(), nullable=True, comment='Preço do produto.'),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True, comment='Limite de estoque baixo.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_product_name'), 'inventory', ['product_name'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único da venda.'),
    sa.Column('product_name', sa.String(), nullable=True, comment='Identificador único do produto.'),
    sa.Column('quantity', sa.Integer(), nullable=True, comment='Quantidade do produto comprado.'),
    sa.Column('total_value', sa.Float(), nullable=True, comment='Valor total da venda.'),
    sa.Column('customer_id', sa.String(), nullable=True, comment='Identificador único do cliente.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_id'), 'sales', ['id'], unique=False)
    op.create_index(op.f('ix_sales_product_name'), 'sales', ['product_name'], unique=False)
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único do pet.'),
    sa.Column('name', sa.String(), nullable=True, comment='Nome do pet.'),
    sa.Column('breed', sa.String(), nullable=True, comment='Raça do pet.'),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True, comment='Data de nascimento do pet.'),
    sa.Column('customer_id', sa.Integer(), nullable=True, comment='Identificador único do cliente.'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_breed'), 'pets', ['breed'], unique=False)
    op.create_index(op.f('ix_pets_customer_id'), 'pets', ['customer_id'], unique=False)
    op.create_index(op.f('ix_pets_date_of_birth'), 'pets', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_pets_id'), 'pets', ['id'], unique=False)
    op.create_index(op.f('ix_pets_name'), 'pets', ['name'], unique=False)
    op.create_table('vaccines',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único da vacina.'),
    sa.Column('pet_id', sa.Integer(), nullable=True, comment='Identificador único do pet.'),
    sa.Column('vaccine_name', sa.String(), nullable=True, comment='Nome da vacina.'),
    sa.Column('date_of_application', sa.DateTime(), nullable=True, comment='Data da aplicação da vacina.'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vaccines_date_of_application'), 'vaccines', ['date_of_application'], unique=False)
    op.create_index(op.f('ix_vaccines_id'), 'vaccines', ['id'], unique=False)
    op.create_index(op.f('ix_vaccines_pet_id'), 'vaccines', ['pet_id'], unique=False)
    op.create_index(op.f('ix_vaccines_vaccine_name'), 'vaccines', ['vaccine_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vaccines_vaccine_name'), table_name='vaccines')
    op.drop_index(op.f('ix_vaccines_pet_id'), table_name='vaccines')
    op.drop_index(op.f('ix_vaccines_id'), table_name='vaccines')
    op.drop_index(op.f('ix_vaccines_date_of_application'), table_name='vaccines')
    op.drop_table('vaccines')
    op.drop_index(op.f('ix_pets_name'), table_name='pets')
    op.drop_index(op.f('ix_pets_id'), table_name='pets')
    op.drop_index(op.f('ix_pets_date_of_birth'), table_name='pets')
    op.drop_index(op.f('ix_pets_customer_id'), table_name='pets')
    op.drop_index(op.f('ix_pets_breed'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_sales_product_name'), table_name='sales')
    op.drop_index(op.f('ix_sales_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_inventory_product_name'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_address'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_bookings_service_name'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_scheduled_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_pet_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_employee_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
